// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, GetQuestionsData, GetQuestionsResponse, GetQuestionsResponses, PostQuestionsData, PostQuestionsResponses, QuestionListItem, QuestionSubmissionItem, SubmittedAnswer } from './types.gen';
