// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://qa_api.dev.localhost:9300/' | (string & {});
};

export type QuestionListItem = {
    id?: string;
    title?: string;
    content?: string;
    submittedAnswers?: null | Array<SubmittedAnswer>;
};

export type QuestionSubmissionItem = {
    title: string;
    content: string;
    priority: number | string;
};

export type SubmittedAnswer = {
    id?: string;
    content?: string;
};

export type GetQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/questions';
};

export type GetQuestionsResponses = {
    /**
     * OK
     */
    200: Array<QuestionListItem>;
};

export type GetQuestionsResponse = GetQuestionsResponses[keyof GetQuestionsResponses];

export type PostQuestionsData = {
    body: QuestionSubmissionItem;
    path?: never;
    query?: never;
    url: '/questions';
};

export type PostQuestionsResponses = {
    /**
     * OK
     */
    200: unknown;
};
