// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zQuestionSubmissionItem = z.object({
    title: z.string().min(5).max(50),
    question: z.string().min(30).max(500),
    priority: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zSubmittedAnswer = z.object({
    id: z.optional(z.uuid()),
    question: z.optional(z.string())
});

export const zQuestionListItem = z.object({
    id: z.uuid(),
    title: z.optional(z.string().min(5).max(100)),
    question: z.string().min(30).max(500),
    submittedAnswers: z.optional(z.union([
        z.null(),
        z.array(zSubmittedAnswer)
    ]))
});

export const zGetQuestionsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zGetQuestionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetQuestionsResponse = z.array(zQuestionListItem);

export const zPostQuestionsData = z.object({
    body: zQuestionSubmissionItem,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
